### ISSUE TITLE
ElBa ZIP file is corrupt

### ISSUE THREAD

**Issue by Shankhanil** [godimarcovr/Texel-Att#1]
Tried downloading the ElBa dataset from the drive link, but unfortunately the file is corrupt and am not able to extract. 

![image](https://user-images.githubusercontent.com/17963889/187364740-41e59eb6-6f03-4cc7-8290-ba36ec1fb4eb.png)

**Comment by joppichristian** [comment]
Hi Shankhanil,
thanks for sharing this issue.
I just provided to replace the archive with a new one not corrupted.
