### ISSUE TITLE
ElBa ZIP file is corrupt

### ISSUE THREAD

**Issue by Tgaaly** [godimarcovr/Texel-Att#2]
I cannot uncompress this dataset. I have tried multiple times but I get errors when unzipping the file. I've tried on my macbook and using google drive 3rd party unzip program

**Comment by joppichristian** [comment]
Hi Tgaaly,
thanks for rising up this issue.
It seems that the problem is on Linux/Mac OS. 

Try this command: 
`
zip -FF elba.zip --out fix_elba.zip
unzip fix_elba.zip
`

**Comment by joppichristian** [comment]
Hi Tgaaly,
thanks for rising up this issue.
It seems that the problem is on Linux/Mac OS. 

Try these commands: 
`
zip -FF elba.zip --out fix_elba.zip
`
`
unzip fix_elba.zip
`

**Comment by Tgaaly** [comment]
thank you that fixed it. appreciate the swift response
